CREATE TABLE cameras (
    id BIGINT NOT NULL AUTO_INCREMENT,
    stable_key VARCHAR(512) NOT NULL,
    endpoint_urn VARCHAR(512) NULL,
    name VARCHAR(160) NOT NULL,
    host VARCHAR(255) NOT NULL,
    device_service_url VARCHAR(1000) NOT NULL,
    media_service_url VARCHAR(1000) NULL,
    ptz_service_url VARCHAR(1000) NULL,
    manufacturer VARCHAR(160) NULL,
    model VARCHAR(160) NULL,
    firmware_version VARCHAR(160) NULL,
    serial_number VARCHAR(160) NULL,
    username VARCHAR(160) NULL,
    encrypted_password TEXT NULL,
    profile_token VARCHAR(512) NULL,
    rtsp_uri VARCHAR(2000) NULL,
    ptz_supported BOOLEAN NOT NULL DEFAULT FALSE,
    online BOOLEAN NOT NULL DEFAULT FALSE,
    detection_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    detection_prompt TEXT NULL,
    detection_interval_seconds INT NOT NULL DEFAULT 30,
    confidence_threshold DECIMAL(4,3) NOT NULL DEFAULT 0.600,
    last_seen_at TIMESTAMP(6) NULL,
    last_connected_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_cameras_stable_key (stable_key),
    KEY idx_cameras_online (online),
    KEY idx_cameras_detection (detection_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE detection_events (
    id BIGINT NOT NULL AUTO_INCREMENT,
    camera_id BIGINT NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    confidence DECIMAL(5,4) NOT NULL,
    summary VARCHAR(1000) NOT NULL,
    raw_response MEDIUMTEXT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_events_camera_time (camera_id, occurred_at DESC),
    KEY idx_events_time (occurred_at DESC),
    CONSTRAINT fk_events_camera FOREIGN KEY (camera_id) REFERENCES cameras(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

